Vagrant.configure("2") do |config|
  #config.vm.provision "shell", inline:<<-SHELL
  #echo 'start to install VBoxGuestAdditions'
  #yum -y install wget
  #wget http://download.virtualbox.org/virtualbox/4.3.8/VBoxGuestAdditions_4.3.8.iso
  #mkdir /media/VBoxGuestAdditions
  #mount -o loop,ro VBoxGuestAdditions_4.3.8.iso /media/VBoxGuestAdditions
  #sudo sh /media/VBoxGuestAdditions/VBoxLinuxAdditions.run
  #rm VBoxGuestAdditions_4.3.8.iso
  #echo 'install VBoxGuestAdditions'
  #echo 'starting to install ansible'
  #echo "10.0.0.1 machine1" >> /etc/hosts
  #echo "10.0.0.2 machine2" >> /etc/hosts
  #yum -y install epel-release
  #yum -y install ansible
  #echo 'ansible installed'
  #sudo apt-get install linux-headers-$(uname -r) build-essential dkms
  #SHELL

  config.vm.define "machine1" do |machine1|
    machine1.vm.provision "shell", inline:<<-SHELL
    echo 'starting to allow password connection by ssh'
    sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
    sudo systemctl restart sshd
    echo 'password connection allowed'
    SHELL

    machine1.vm.box = "centos/7"
    machine1.vm.box_url = "https://vagrantcloud.com/centos/7"
    machine1.vm.hostname = "machine1"
    #machine1.vm.synced_folder "../../ansible-scripts", "/ansible-scripts"
    machine1.vm.network "private_network", ip: "10.0.0.1"
    machine1.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
    end
  end


  config.vm.define "machine2" do |machine2|
    machine2.vm.provision "shell", inline:<<-SHELL
    echo 'starting to create ssh key'
    ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N "" <<<y 2>&1 >/dev/null
    echo 'ssh key created'
    sudo yum install sshpass
    yes | sshpass -p "vagrant" ssh-copy-id -i ~/.ssh/id_rsa.pub vagrant@machine1
    echo 'ssh key copied into machine1'
    SHELL

    machine2.vm.box = "centos/7"
    machine2.vm.box_url = "https://vagrantcloud.com/centos/7"
    machine2.vm.hostname = "machine2"
    machine2.vm.network "private_network", ip: "10.0.0.2"
    machine2.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
    end
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
