Vagrant.configure("2") do |config|
  config.vm.provision :shell, inline:<<-SHELL
  echo "10.0.0.1 machine1" >> /etc/hosts
  echo "10.0.0.2 machine2" >> /etc/hosts
  SHELL

  config.vm.define "machine1" do |machine1|
    machine1.vm.box = "centos/7"
    machine1.vm.box_url = "https://vagrantcloud.com/centos/7"
    machine1.vm.hostname = "machine1"
    machine1.vm.network "private_network", ip: "10.0.0.1"
    machine1.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
    end
  end


  config.vm.define "machine2" do |machine2|
    machine2.vm.box = "centos/7"
    machine2.vm.box_url = "https://vagrantcloud.com/centos/7"
    machine2.vm.hostname = "machine2"
    machine2.vm.network "private_network", ip: "10.0.0.2"
    machine2.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
    end
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
